AllCops:
  TargetRubyVersion: 2.2.4

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false